spring:
  application:
    name: credit-score-service

  datasource:
    url: jdbc:postgresql://localhost:5432/zbank_creditscore
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: zbank-credit-score-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: "*"


server:
  port: 8082

zbank:
  kafka:
    consumer:
      customer-application:
        group-id: zbank-credit-score-group

logging:
  level:
    org.springframework.kafka: INFO
    org.apache.kafka: WARN